esphome:
  name: desk
  platform: ESP8266
  board: esp01_1m

external_components:
  - source: github://TillFleisch/ESPHomeGenericSitStandDesk@main

# Enable logging
logger:
  baud_rate: 0

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 57600

# Enable Home Assistant API
api:

ota:
  password: "HaHaGetRickRolled"

wifi:
  ssid: !secret WiFi_Name
  password: !secret WiFi_Password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desk Fallback Hotspot"
    password: "dQw4w9WgXcQ"

captive_portal:

generic_desk:
  id: desk1
  uart_id: uart_bus
  # The Desks height measured in the lowest position
  base_height: 66.4
  #Optional correction factor, in case the height does not scale properly
  correction_term: 1.24836

sensor:
  - platform: desk_height_sensor
    desk_id: desk1
    id: desk_height
    name: "Desk Height"

binary_sensor:
 - platform: desk_is_moving_sensor
   desk_id: desk1
   id: desk_is_moving
   name: "Desk is Moving"

switch:
  - platform: desk_switch
    desk_id: desk1
    name: "Up"
    direction: true

  - platform: desk_switch
    desk_id: desk1
    name: "Down"
    direction: false  

button:
  - platform: desk_memory_button
    desk_id: desk1
    name: "M1"
    memory_id: 1

  - platform: desk_memory_button
    desk_id: desk1
    name: "M2"
    memory_id: 2

  - platform: desk_memory_button
    desk_id: desk1
    name: "M3"
    memory_id: 3

  - platform: desk_memory_button
    desk_id: desk1
    name: "M4"
    memory_id: 4


